#!/usr/bin/env ruby
# frozen_string_literal: true

# Fast launcher for kenshin without gem warnings

# Suppress all warnings
$VERBOSE = nil

# Direct load without rubygems overhead
require_relative '../lib/kenshin/cli'

Kenshin::CLI.start(ARGV)
