#!/usr/bin/env ruby
# Fast launcher for rfmt without gem warnings

# Suppress all warnings
$VERBOSE = nil

# Direct load without rubygems overhead
require_relative '../lib/rfmt/cli'

Rfmt::CLI.start(ARGV)